CREATE TABLE noticia(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(70) NOT NULL,
    conteudo VARCHAR(500) NOT NULL,
    data_publi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    imagem_url VARCHAR(300)
)